### ISSUE TITLE
Tudo é estático

### ISSUE THREAD

**Issue by aquelehugo** [DennyLoko/pokemongonobr#1]
Quando o Pokemon Go sair, esse repositório terá que ser atualizado manualmente.
Favor criar uma maneira de descobrir se o acesso ao Pokemon Go está liberado através de uma API ou algo do tipo.

**Comment by DennyLoko** [comment]
@aquelehugo,
Eu abri o código do repositório justamente para que a comunidade possa ajudar com as melhorias. Ficarei muito grato se puder fazer isso. ❤️

**Comment by aquelehugo** [comment]
@DennyLoko Desculpa aew, sou só um artista -> http://aquelehugo.com

**Comment by DennyLoko** [comment]
@aquelehugo: Ok, depois vou ver o que eu posso fazer aqui...
