### ISSUE TITLE
Colocar alguma imagem no site

### ISSUE THREAD

**Issue by aquelehugo** [DennyLoko/pokemongonobr#2]
Sugestão:

![image](https://cloud.githubusercontent.com/assets/8480411/17381231/4a904052-59a1-11e6-9685-dc8b98a18e3e.png)

**Comment by wesleycsj** [comment]
Vou fazer isso!

**Comment by luizbaldi** [comment]
Oi! A issue foi resolvida? Gostaria de contribuir caso ainda esteja em aberto.

**Comment by aquelehugo** [comment]
Não foi. Você pode conferir em https://jasaiupokemongonobrasil.xyz/
No entanto, sugiro que use outra imagem, de um Pikachu feliz, já que Pokemon GO saiu no Brasil já.

**Comment by wesleycsj** [comment]
@aquelehugo Eu abri PR há dias já! #3

**Comment by aquelehugo** [comment]
@wesleycsj Valeu =D

**Comment by DennyLoko** [comment]
Desculpa a demora, galera! Eu não recebi notificação de comentários nessa issue aqui.

@wesleycsj Não sei se você está participando do [Hacktoberfest](https://hacktoberfest.digitalocean.com/), se sim, você tem que linkar o PR à está issue aqui, para funcionar...

**Comment by wesleycsj** [comment]
@DennyLoko Obrigado por lembrar, tinha esquecido, porem não houve necessidade, o sistema do Hacktoberfest ja pegou que eu fiz PR's suficientes msm assim, em todo caso vou linkar. #3
